// Throwaway composition study: three structures using the real workspace snapshot.
// The chosen atlas is implemented separately in the authored viewer.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { Snapshot } from "../src/viewer/types";
const path=Bun.argv[2]??"data/design-workspace/workspace.snapshot.json";
const snapshot=JSON.parse(readFileSync(path,"utf8")) as Snapshot;
const data=JSON.stringify(snapshot.sample?.projects??[]).replace(/</g,"\\u003c");
const output=join(dirname(path),"ui-prototype.html");
writeFileSync(output,`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tomeowl UI composition study</title><style>
*{box-sizing:border-box}body{margin:0;background:#151716;color:#ecede5;font:14px 'Segoe UI',sans-serif}header{padding:22px 30px;border-bottom:1px solid #333a34;display:flex;justify-content:space-between;color:#ecae7d}h1{font-size:28px;font-weight:500}h2{font-size:18px;font-weight:500}p{color:#a5ada4;line-height:1.7}main{padding:30px 40px 120px;max-width:1300px;margin:auto}button{background:#242824;border:1px solid #4a554b;color:#ecede5;border-radius:5px;padding:9px 14px;cursor:pointer}.switcher{position:fixed;bottom:24px;left:50%;transform:translateX(-50%);display:flex;gap:18px;align-items:center;padding:10px;background:#342b23;border:1px solid #ecae7d;border-radius:8px}.atlas{display:grid;grid-template-columns:190px 1fr 230px;gap:30px}.cloud{display:grid;grid-template-columns:repeat(5,1fr);gap:26px;text-align:center}.cloud article{padding:18px 0}.cloud i{display:block;width:42px;height:42px;border:1px dashed #9ec9ba;border-radius:50%;margin:0 auto 10px;color:#9ec9ba;line-height:40px}.desk{display:grid;grid-template-columns:240px 1fr;gap:32px}.desk article{padding:15px 0;border-bottom:1px solid #333a34;display:flex;justify-content:space-between}.stack{display:grid;gap:30px}.stack section{padding:22px;background:#202721;display:grid;grid-template-columns:150px 1fr}.stack article{display:inline-block;padding:8px 16px;color:#9ec9ba}small{color:#a5ada4}.state{font:12px Consolas,monospace;background:#202721;padding:14px;color:#a5ada4}@media(max-width:740px){main{padding:24px 18px 120px}.atlas,.desk{display:block}.cloud{grid-template-columns:repeat(3,1fr)}.stack section{display:block}.switcher{width:calc(100% - 24px);justify-content:space-between;gap:8px}}
</style><header><strong>tomeowl. / composition study</strong><small>Throwaway · no mutations</small></header><main id="study"></main><div class="switcher"><button id="prev" aria-label="Previous composition">Previous</button><span id="label"></span><button id="next" aria-label="Next composition">Next</button></div><script>
const projects=${data};const variants=['atlas','desk','layers'];const names=['Spatial atlas','Reading desk','Layer stack'];let index=Math.max(0,variants.indexOf(new URL(location.href).searchParams.get('variant')));const escape=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function render(){const groups=projects.map(p=>'<article><i>'+p.sourceIds.length+'</i><strong>'+escape(p.title)+'</strong></article>').join('');const rows=projects.map(p=>'<article><strong>'+escape(p.title)+'</strong><small>'+p.sourceIds.length+' selected sources</small></article>').join('');document.querySelector('#label').textContent=names[index];let body=index===0?'<div class="atlas"><aside><h2>Explore</h2><p>Projects<br>Research<br>Main docs<br>Skills<br>Apps</p></aside><section><h1>Your connected workspace</h1><p>Named project groups open into source neighborhoods.</p><div class="cloud">'+groups+'</div></section><aside><h2>Evidence</h2><p>A stable reading panel follows the selected source.</p></aside></div>':index===1?'<div class="desk"><aside><h2>Research index</h2><p>Corpus and project filters lead. The map becomes a secondary connection preview.</p></aside><section><h1>Browse first, connect next</h1>'+rows+'</section></div>':'<h1>A workspace in layers</h1><p>Horizontal levels lead. The map shows where each project sits in the document / skill / app stack.</p><div class="stack">'+['Main Markdown','Skills and reusable tools','Apps and supporting documents'].map(l=>'<section><h2>'+l+'</h2><div>'+projects.slice(0,12).map(p=>'<article>'+escape(p.title)+'</article>').join('')+'</div></section>').join('')+'</div>';document.querySelector('#study').innerHTML=body+'<p class="state">State: variant='+variants[index]+' · projects='+projects.length+' · read only · selected=none</p>';const url=new URL(location.href);url.searchParams.set('variant',variants[index]);history.replaceState(null,'',url);}
function cycle(delta){index=(index+delta+variants.length)%variants.length;render()}document.querySelector('#prev').onclick=()=>cycle(-1);document.querySelector('#next').onclick=()=>cycle(1);document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(e.target.tagName)||e.target.isContentEditable)return;if(e.key==='ArrowLeft')cycle(-1);if(e.key==='ArrowRight')cycle(1)});render();
</script></html>`);
console.log(JSON.stringify({ok:true,output,selectedDirection:"atlas",variants:["atlas","desk","layers"]}));
